### ISSUE TITLE
Créer une structure avec des dossiers

### ISSUE THREAD

**Issue by droumanet** [Brieuc-Meyer/Chasse_au_tresor#1]
Cela permet de mieux organiser votre travail.

**Comment by Brieuc-Meyer** [comment]
![image](https://user-images.githubusercontent.com/98985962/168012940-a460a0d4-9925-461e-ab18-2a7edc89a9fb.png)

**Comment by droumanet** [comment]
Erreur de github (j'ai plusieurs onglets de chacun), désolé.
